[package]
name = "voronoify-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
image = "0.24"
clap = { version = "4.2", features = ["derive"] }
kdtree = "0.7"
rand = "0.8"
rand_chacha = "0.3"
rayon = "1.11"
